
#require(survival)
#tdat <- subset(surgerydat, Hosp_num == 1)
#tcbaseh <- function(t) chaz_exp(t, lambda = 0.01)
#exprfit <- as.formula("Surv(survtime, censorid) ~ age + sex + BMI")
#tcoxmod <- coxph(exprfit, data= surgerydat)
##Alternatively, cbaseh can be left empty when specifying coxphmod through coxph()
##require(tictoc)
##tic("zonder cores")
#cgr <- cgrcusum(data = tdat, coxphmod = tcoxmod, cbaseh = tcbaseh, pb = FALSE)
##toc()
##tic("met cores")
#cgr2 <- cgrcusum(data = tdat, coxphmod = tcoxmod, cbaseh = tcbaseh, ncores = 6)
##toc()
#all.equal(cgr$CGR, cgr2$CGR)
