# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Active_Individuals_Lambdamat_rows <- function(helperstime, ctime, entrytimes) {
    .Call(`_success_Active_Individuals_Lambdamat_rows`, helperstime, ctime, entrytimes)
}

sumC <- function(x) {
    .Call(`_success_sumC`, x)
}

